### ISSUE TITLE
Cannot access WebUI over network

### ISSUE THREAD

**Issue by lewiswalsh** [SebDanielsson/compose-transmission-wireguard#16]
Wireguard is connecting, I have confirmed this by issuing a curl command within the container.

Using `docker network inspect bridge` I have confirmed by docker network bridge to be 172.17.0.1:
```
[
    {
        "Name": "bridge",
        "Id": "<removed>",
        "Created": "2023-03-06T13:33:47.813766591Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
```

My `wg0.conf` looks like this:
```
[Interface]
PrivateKey = <removed>
Address = 10.64.216.208/32,fc00:bbbb:bbbb:bb01::1:d8cf/128
DNS = 10.64.0.1
ListenPort = 51820
PostUp = ip route add 192.168.1.0/24 via 172.17.0.1
PreDown = ip route delete 192.168.1.0/24

[Peer]
PublicKey = <removed>
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 193.138.218.220:51820
```

The log shows wireguard is binding 192.168.1.0 (my LAN) to 172.17.0.1:
```
wireguard_1       | [#] ip route add 192.168.1.0/24 via 172.17.0.1
```

If I curl to localhost:9091 on the server I get a response from transmission, but if I try to access from elsewhere on my LAN, the connection just times out. I have no firewall running on the server, and I can access other docker containers' web interfaces on the same IP.

What am I missing?

**Comment by sebdanielsson** [comment]
What does your compose file look like?

**Comment by lewiswalsh** [comment]
```
services:
  wireguard:
    image: linuxserver/wireguard:version-v1.0.20210914
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    ports:
      - "9091:9091/tcp"
    volumes:
      - ./wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    restart: always
  transmissionwg:
    image: linuxserver/transmission:version-3.00-r5
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - TRANSMISSION_WEB_HOME=/transmissionic/
    env_file:
      - ./transmission.env
    volumes:
      - ./transmission-config:/config
      - "/local/media/tor:/downloads"
      - "/local/media/tor/watch:/watch"
    restart: always
```

transmission.env:
```
USER=<removed>
PASS=<removed>
PEERPORT=54914
```
