### ISSUE TITLE
Request: Give more insight on secure ways to access transmission webui

### ISSUE THREAD

**Issue by alexg-k** [SebDanielsson/compose-transmission-wireguard#17]
As someone who is not experienced in docker networking, I kindly request an example for a recommended way to access the webui. In the Readme you write: 

> The Transmission WebUI is accessible at 127.0.0.1:9091. I highly recommend to use a VPN to access your WebUI remotely.

This sounds to me that the webui is only accessible from inside the docker network of the wireguard container or via the VPN. I was not aware that different clients using the same VPN can communicate with eachother. Surely it would be tiresome to give a configuration example for every VPN provider you mention in the readme. In the next section you continue:

> If your wg0.conf is configured to route all traffic through the VPN server you'll need to add a route to open up for local access. ...

This sounds to me like this solution is not 'recommended' and the added routes increase the risk for IP leaks . Also the IP address from the wireguard service seemed to be changing during my experimentations (removing and restarting containers).

Lastly I read about using a reverse proxy that forwards requests from the host network to the closed wireguard network, which sounds to me like the best solution. My idea / kind request to you or others is to provide a (commented by default?) configuration in the compose file for a working reverse proxy service.  Surely this would resolve some worries for the newbies :)

Btw thanks for this repo. I appreciate it.

**Comment by sebdanielsson** [comment]
I've used both Traefik and Cloudflare Zero Access to access my various services. I'll definitely write something up to show you how to do this with Traefik. I'll try to find time to do this soon and also create some examples for integration with Radarr, Sonarr etc!☺️

**Comment by sebdanielsson** [comment]
Hi again! Sorry for the late reply. Been pretty busy with school and stuff.

With the current configuration you're able to access the WebUI from the host OS through port 9091. You'll also be able to access it from any computer on the same network as your host, if you have firewalld or something similar you'll just want to open port 9091 on that firewall as well.

My favorite solution from a security perspective is to install Tailscale on your clients and your Docker host. This way you can access the WebUI from your phone, computers etc without the need to open ports on your Linux firewall. And you will be able to access it anywhere, all without the need to open ports and exposing yourself to to the internet.

The second best would be to setup a Wireguard server on your Docker host and connect to it from your devices. However that'll require you to open ports on your firewall(s).

[Tailscale](https://tailscale.com) is free for personal use.

If you for some reason don't want to use Tailscale I actually wrote a guide to setup a Wireguard server a couple of years ago.😃 
[Install WireGuard [Server] on Arch Linux](https://hogwarts.zone/install-wireguard-server-on-arch-linux)

This was before I containerized my services but I know that LinuxServer.io guys have pretty good documentation to get started with a WireGuard Server with Docker.

**Comment by sebdanielsson** [comment]
Also here's my compose files for setting up Prowlarr, Radarr and Sonarr:

Prowlarr: https://github.com/sebdanielsson/infra/blob/main/docker/prowlarr/compose.yaml
Radarr: https://github.com/sebdanielsson/infra/blob/main/docker/radarr/compose.yaml
Sonarr: https://github.com/sebdanielsson/infra/blob/main/docker/sonarr/compose.yaml

**Comment by alexg-k** [comment]
Hi Sebastian,

I have experimented a little bit more and I propose another, maybe the easiest (and safe?) solution:

Honestly, I am a little baffled. I setup a reverse proxy on my docker **host** using nginx and it has access to the webui of transmission without adding any additional routes to the wireguard container. 

This is my setup:
`compose.yaml`:
```
services:
  wireguard:
    image: linuxserver/wireguard:version-v1.0.20210914
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - "9091:9091/tcp"
    volumes:
      - ./wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    restart: unless-stopped
  
  transmission:
    image: linuxserver/transmission
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    env_file:
      - ./transmission.env
    volumes:
      - ./transmission-config:/config
      - /storage/downloads:/downloads
      - ./watch:/watch
    restart: unless-stopped
```

`wg0.conf`:
```
[Interface]
PrivateKey = <private_key>
Address = <ipv4>/32
DNS = <ipv4>

[Peer]
PublicKey = <public_key>
AllowedIPs = 0.0.0.0/0
Endpoint = <ipv4>:51820
```

`nginx_transmission.conf`:
```
     server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name download.nas.lan;

        access_log /var/log/nginx/transmission.access.log;
        error_log /var/log/nginx/transmission.error.log;

        ssl_certificate /etc/ssl/nas.lan.crt;
        ssl_certificate_key /etc/ssl/nas.lan.key; 

	client_max_body_size 0;

	location / {
	    proxy_pass http://127.0.0.1:9091;
	    proxy_pass_header X-Transmission-Session-Id;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
    }
```

Crazy, accessing http://nas.lan:9091 from my machine does not work, but the reverse proxy has access. Torrenting works.
