### ISSUE TITLE
Cannot access webui, everything else works fine

### ISSUE THREAD

**Issue by crypticwhisker** [SebDanielsson/compose-transmission-wireguard#20]
Very similar to [this](https://github.com/sebdanielsson/compose-transmission-wireguard/issues/16). I recently updated Docker and now I can't reach the web ui for transmission.

`curl https://am.i.mullvad.net/connected` returns true in both the wireguard and transmission containers, so it seems like transmission is using wireguard as its network service.

I'm a bit confused by two things:
- I never used `PostUp` or `PreDown` previously. If I do add them to my `wg0.conf`, then the mullvad connection check fails.
- I changed nothing outside of updating Docker, so I'm not sure where/what changed.

Anyone else running into this?

compose.yaml
```
services:
  wireguard:
    image: linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - "9091:9091/tcp"
    volumes:
      - ./wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    restart: always
  transmission:
    image: linuxserver/transmission:latest
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    env_file:
      - ./transmission.env
    volumes:
      - ./transmission-config:/config
      - ./downloads:/downloads
      - ./watch:/watch
      - ./scripts:/scripts
    restart: always
```

**Comment by sebdanielsson** [comment]
Sorry for the slow reply. If you haven't gotten it up and running yet. Please post your `wg0.conf` or make sure that you're using the right IP address and subnet. You might need to set a static IP for the Docker network to avoid receiving new IP addresses after each recreation.

**Comment by crypticwhisker** [comment]
No worries. Here's my `wg0.conf`

```
[Interface]
PrivateKey = <removed>
Address = 10.65.171.180/32,fc00:bbbb:bbbb:bb01::2:abb3/128
DNS = 10.64.0.1
PostUp = ip route add 192.168.2.0/24 via 172.17.0.1;
PreDown = ip route delete 192.168.2.0/24;

[Peer]
PublicKey = <removed>
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 87.249.134.1:51820
PersistentKeepAlive = 60
```

**Comment by sebdanielsson** [comment]
Looks good. And what is your container ip for the wireguard container?

**Comment by crypticwhisker** [comment]
`docker inspect` returns

```
"Gateway": "172.17.0.1",
"IPAddress": "172.17.0.2",
```

Logs show the bind as well

`2023-10-17 13:28:33 [#] ip route add 192.168.2.0/24 via 172.17.0.1`

**Comment by sebdanielsson** [comment]
That's so strange... Can't see why that wouldn't work. And I assume the computer you're trying to connect from is on the same network as the server? And have an 192.168.2.x IP address?

**Comment by crypticwhisker** [comment]
I can’t even reach the web UI from the server itself. I wonder if the bridge is just borked.

**Comment by crypticwhisker** [comment]
Almost certain this is mullvad. My networking chops aren't good enough to sus out exactly where things are broken. Call this resolved.

**Comment by crypticwhisker** [comment]
Sorry to zombie this but I found something interesting. The comments on #16 mentioned that this due to using the wrong bridge.

`docker inspect bridge` returns

```
"Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
```

whereas `docker inspect dockmission` returns

```
"Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "192.168.192.0/20",
                    "Gateway": "192.168.192.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "5148b8e497d58a92c9a26c48dcc54e9144c9cb9f26ecc8b4cf6ac602bf039c4a": {
                "Name": "dockmission-wireguard-1",
                "EndpointID": "ae658f6e4447c1268cc261af3f3d6a925e00580f52b628e053dbe493dec26f1d",
                "MacAddress": "02:42:c0:a8:c0:02",
                "IPv4Address": "192.168.192.2/20",
                "IPv6Address": ""
            }
        },
```

So the wireguard container is using `dockmission_default` which somehow has an IP in the 192 range? Shouldn't the docker engine be setting up in the 172 range? I have another container set up that is also in the 172, just like bridge is.

**Comment by sebdanielsson** [comment]
Hi! I'll compare with my setup. A workaround that might work is to define the network in the compose file. Just need to do some school work first and I'll get back to you ASAP😃

**Comment by sebdanielsson** [comment]
Here's my personal `compose.yaml`:

```yaml
---
services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wgnet:
        ipv4_address: 172.100.0.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    ports:
      - 9091:9091
    volumes:
      - /lib/modules:/lib/modules
      - ./wg0.conf:/config/wg0.conf
    restart: always
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
  transmission:
    image: linuxserver/transmission:version-4.0.3-r2
    container_name: transmission
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    env_file:
      - secrets.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - DOCKER_MODS=jordanpotter/docker-mods:transmission-nat-pmp
    volumes:
      - transmission_data:/config
      - /chungus/media/downloads:/downloads
    restart: always

networks:
  wgnet:
    ipam:
      config:
        - subnet: 172.100.0.0/24
          ip_range: 172.100.0.0/24
          gateway: 172.100.0.1
    attachable: true

volumes:
  transmission_data:
    name: transmission_data
```

Note this under the wireguard service:

```yaml
networks:
      wgnet:
        ipv4_address: 172.100.0.2
```

and this at the top level:

```yaml
networks:
  wgnet:
    ipam:
      config:
        - subnet: 172.100.0.0/24
          ip_range: 172.100.0.0/24
          gateway: 172.100.0.1
    attachable: true
```
