### ISSUE TITLE
conflict during startup

### ISSUE THREAD

**Issue by hemna** [SebDanielsson/compose-transmission-wireguard#25]
I'm using a version of your compose to start transmission and wireguard. The problem I'm having is that docker is complaining about the transmission network_mode 

```
waboring@docker-vm:~/docker/torrent$ docker compose up
[+] Running 3/5
 ✔ Network torrent_default        Created                                                                                                                           0.2s
 ✔ Container torrent-wireguard-1  Created                                                                                                                           1.0s
 ⠋ Container transmission         Creating                                                                                                                          0.0s
Error response from daemon: conflicting options: port publishing and the container type network mode
```

```
services:
  wireguard:
    #image: linuxserver/wireguard:version-v1.0.20210914
    image: linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - "9091:9091/tcp"
    volumes:
      - ./wg-oracle.conf:/config/wg_confs/wg0.conf
      - /lib/modules:/lib/modules
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    depends_on:
      - wireguard
    network_mode: "service:wireguard"
    env_file:
      - ./transmission.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TZ=America/New_York
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - /mnt/pve-share/torrent/transmission/data:/config
      - /mnt/pve-share/torrent/transmission/downloads:/downloads #optional
      - ./watch:/watch #optional
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
```
