### ISSUE TITLE
Example config for LAN access

### ISSUE THREAD

**Issue by jshank** [SebDanielsson/compose-transmission-wireguard#5]
I'd love to use this stack but just can't figure out how to get LAN access to the web interface. I was able to setup an SSH tunnel but, short of that, I wasn't able to get to the transmission webui. I've tried traefik as configured below without success. The compose file is exactly like the sample otherwise.

```
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    ports:
      - 9091:9091/tcp
...
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.example.com`)"
      - "traefik.http.routers.transmission.tls.certresolver=cloudflare"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
```
